### ISSUE TITLE
Currently working?

### ISSUE THREAD

**Issue by ColossalCalamari** [Detergent13/tft-bot#1]
Hi there. Is this software currently working? I'm trying to run the python scripts but running into a few errors. Just wanted to check with you first before I spend too much time debugging. Thanks!

**Comment by Detergent13** [comment]
Hi- should be working for the most part, although you may have to re-do some of the images in the ./captures/ folder yourself (specifically the champion photos since they're from the old set). If you do so, please feel free to open up a pull request with the changes! Everything else should be in good shape, and make sure that you have the correct Python/module versions especially, since this seems to cause most of the issues that I've seen so far.

**Comment by ColossalCalamari** [comment]
Thanks for responding :) I got it working (I think!), the issue was Numpy 1.19.4:

https://stackoverflow.com/questions/64729944/runtimeerror-the-current-numpy-installation-fails-to-pass-a-sanity-check-due-to

> The temporary solution is to use numpy 1.19.3.
> pip install numpy==1.19.3

Will mess with the images and stuff this weekend and will open up a pull request once I do. Thanks again!

**Comment by Detergent13** [comment]
Glad to hear it! Haven't heard that one before, so thanks for the info. Hope it works out for you, and thank you for contributing!

**Comment by Detergent13** [comment]
Updated for Set 4.5 as of today!
