### ISSUE TITLE
8.5 PBE Issue with Surrender

### ISSUE THREAD

**Issue by RomeoAlphaEkko** [Detergent13/tft-bot#117]
As of today the surrender button has been "greyed" out.

Surrender is only possible by typing on the keyboard aka /ff

i dont know if it is a bug or not, but if not it will be an inssue once it goes live

**Comment by Detergent13** [comment]
Odd change from Riot lol. Thanks for the heads up, I'll keep an eye out!

**Comment by RomeoAlphaEkko** [comment]
The new loading screen is out, so possible capture is Evelyn in the top right and they changed the options button so most likely a recapture there

**Comment by RomeoAlphaEkko** [comment]
sadly the ff-bug is still there

my first idea was like:

        auto.press('enter')  
        auto.press(['/', 'f', 'f'])
        auto.press('enter') 

but that doesnt seem tow ork

-- 7 days till live

**Comment by Detergent13** [comment]
I'll recapture the loading screen when I get the chance. 

If I remember correctly, `auto`'s key input doesn't work with DirectX games. (Hence why ffing currently works by just clicking on buttons, refreshing doesn't use D, etc.) The solution is to use the `pydirectinput` library for any key inputs. Let me know if that ends up going live and I'll implement it. (I think should be almost the exact same since `pydirectinput` was developed with `pyautogui` in mind?)

**Comment by RomeoAlphaEkko** [comment]
![settings](https://user-images.githubusercontent.com/89660477/225118234-6e322dcd-0039-431c-b6e0-81ec3157141c.png)
![loading](https://user-images.githubusercontent.com/89660477/225118263-4f33bce4-7d33-4130-852f-3f8f5effd4a6.png)

**Comment by RomeoAlphaEkko** [comment]
ok, good news, if it goes like that to live, i have (for me) a working version,

but it depends on the keyboard, so each user might have to update it and it may not be change 7 with .

i think we should wait till it is live next week and then re evaluate

**Comment by RomeoAlphaEkko** [comment]
ok they included it, give me a bit for the pull

**Comment by RomeoAlphaEkko** [comment]
pydirectinput.press('divide') 

is a '-'

**Comment by RomeoAlphaEkko** [comment]
pull request done, tests run successfully
