### ISSUE TITLE
The resolution in description is wrong

### ISSUE THREAD

**Issue by Rafinhi** [Detergent13/tft-bot#4]
Hey, the bot was not progressing further than clicking the "accept" button, I did small debugging by adding some logging to the code:

 if onscreen("./captures/tft logo.png"):
        print("I see tft logo")
        click_to("./captures/find match ready.png")
    while not onscreen("./captures/loading.png"):
        print("Cant see loading screen, clicking on accept instead")
        
 And I got to a conclusion that Lol launcher in fact has to be 1280x720, but the Lol Client should be 1280x960 instead (this is the resolution the default images work with), to fix it just add it to the description :P

Edit: Or there might be some deeper problem coming from differences between windowed/windowed borderless mode of game (Tho changing resolution fixed it for me, and as far as I know adding only height to the window changed proportions of the interface elements)

**Comment by Rafinhi** [comment]
It also works fine with full screen league client. I think then there is no deeper problem then, just a typo (You meant to write launcher instead of client)

**Comment by Detergent13** [comment]
Interesting that it works for you on 1280x960 in-game, since all of the captures were taken from a 1920x1080 in-game resolution- probably just within the tolerance of the CV library. Anyway, just updated the README to better reflect this!

To clarify for anybody having the same issue, use 1920x1080 in-game, and 1280x720 in the client/launcher for best results. 

Thanks for the heads up!
