### ISSUE TITLE
Installation video?

### ISSUE THREAD

**Issue by steffenhengst** [Detergent13/tft-bot#47]
Hello,

would it be possible to create an installation video? Have no experience with Python until now and understand the instructions as a layman unfortunately not. You would help me a lot with an explanatory video!

Thanks in advance.

**Comment by src52** [comment]
Download and install Python version 3.8.3.

Download this repository as a ZIP, and extract it. 

Open the directory in your terminal/command line. Run the commands that the readme specifies.

That's it?

**Comment by Detergent13** [comment]
I probably won't make an installation video in all honesty- not really my area of expertise. Definitely happy to feature a video if anybody does want to make one though! Hope you figured out the installation eventually.

**Comment by jo5000** [comment]
Hey, these instructions seem very simple and I am sorry but I really have no idea on what I'm doing wrong. The part that confuses me most is navigating/opening the install directory in order to run those commands.

**Comment by Detergent13** [comment]
Are you on Windows? If so, use the 'cd' command to navigate to wherever you've downloaded it. So for example, my command line opens in C:\Users\<myname>, so I just type `cd Downloads` to get to where I've downloaded it. (And then run the command in the readme)

**Comment by jo5000** [comment]
Oh thanks for this! Really helped me get to the next step but I'm encountering another problem where it says "'pip' is not recognized as an internal or external command, operable program or batch file."

I followed instructions to install pip and the picture shows this as well I believe but the command "pip install -r requirements.txt" does not work. Thank you for replying though!
![pip](https://user-images.githubusercontent.com/91195902/134762318-84603f4d-97a5-43ed-9f02-0ad4a95e4a56.PNG)
.

**Comment by src52** [comment]
> Oh thanks for this! Really helped me get to the next step but I'm encountering another problem where it says "'pip' is not recognized as an internal or external command, operable program or batch file."
> 
> I followed instructions to install pip and the picture shows this as well I believe but the command "pip install -r requirements.txt" does not work. Thank you for replying though!
> ![pip](https://user-images.githubusercontent.com/91195902/134762318-84603f4d-97a5-43ed-9f02-0ad4a95e4a56.PNG)
> .

Awesome, you're getting close. So, you successfully got pip, but since the executables weren't added to your PATH, the command line doesn't understand what "pip" means.

For the sake of simplicity, you can just directly call the pip executable, since it was added to a folder called "Scripts" in your downloads folder.

In the command, replace "pip" with "C:\Users\jorda\Downloads\Scripts\pip.exe"

However, before you run that command, you need to make sure you're in the correct folder in Downloads.

Have you downloaded this repository as a zip file, and extracted it? If so, the files should be in a subfolder of Downloads (whatever the folder name was that you extracted).

You can use the `cd` command to navigate to the subfolder.

Let me know if you have any questions.

**Comment by jo5000** [comment]
Thank you so much! This was perfect I really do appreciate you telling me exactly what to do honestly I probably needed it haha. I got it to work and it's perfect. Really appreciate this!!
