### ISSUE TITLE
If you set the surrender threshhold too far you will never get out of end game screen

### ISSUE THREAD

**Issue by Rafinhi** [Detergent13/tft-bot#5]
Hello, the logic right now is that we play normally till 2-4 (the carousel), then on 2-5 we go into while not loop like this

```
while not onscreen("./captures/3-2.png"): 
            buy(1)
            click_to("./captures/reroll.png")
            time.sleep(1)

```
If you set it for example to 5-2 (so you get about top 4 most of the time) there is a chance that you might die before it or win before it making the screen go into the endgame screen and thus trapping your forever inside of this loop (since you will never see 5-2 on screen), my suggestion to solve is to actually add some sort of security check for endgame button (i am not sure how compute intensive is the "onscreen" function tho and if we can invoke it freely whenever we feel like it)

**Comment by Detergent13** [comment]
Check out the no-surrender branch, it has most of what you describe! If you still want to surrender but later on, you could probably combine some of the logic.
 https://github.com/Detergent13/tft-bot/tree/no-surrender

**Comment by Rafinhi** [comment]
Thank you for response, the problem with no surrender is that sometimes you get into awkward 8 rounds long matches where you fight for top 1/2 so the result has no impact whatsoever on amount of received tokens from event, but wastes a lot of time, ill see what i can do

PS: How is the work going on merging the Pull request with LCU logic and item balls, would be kinda cool to get the random good units from balls early on :D

**Comment by Detergent13** [comment]
Agreed, my best idea for solving the useless fight for 1st/2nd was checking to see if there are six 0's on the scoreboard (meaning everyone but you and the other person is out), but might be hard to get a good capture/precision. 

Just merged the PR with LCU and orbs to the main branch recently, so feel free to try that out! Haven't gotten around to adding it to the no-surrender branch yet, but probably will when I get the chance. 

Still trying to find a LCU endpoint for the missions 'OK' button and 'skip waiting for stats,' issue being that it's pretty hard to actually test since they pop up so rarely. Just doing it with CV for now.

**Comment by Rafinhi** [comment]
Hey, i see last update was 13 days ago, so looks like it was not merged

**Comment by Detergent13** [comment]
Oops, you're totally right lol- thought I had merged but remembered that I meant to test before doing it. Should be soon, sorry about that!

@BadMaliciousPyScripts just added all of the champ images in their recent commit, with plans to have a .json for meta comps, should be great to have once it's complete. (Maybe could even pull from an API like Blitz or something)

I think I'll probably add a no surrender option to the main branch as well, then just delete the no-surrender branch so that I don't have to manage adding new changes to both

**Comment by BadMaliciousPyScripts** [comment]
First I will for now just write the combo.json myself should work until I have time to find a fitting api for my purpose second I will try to make a function that auto sells champions that aren't needed for the current build and one for giving certain champions in the combo the right items for the combo will hopefully have both completed by Thursday.

**Comment by Benjamin-Berger** [comment]
I'm not entirely sure you want to grab orbs. 

I added something in on my that would grab the orbs, and then look for the coins. The problem is that it would sometimes run over blue orbs which added champions to my bench. Because of the champions on my bench, i could not buy the champions that the script was looking for. This lead to fewer 2 and 3 star champions on the board making me weaker. 

Overall this lead to me placing lower on the bracket. At present time I think the fastest way of getting coins reliably is surrendering once 4 people are dead. 

One final note is that this works so well because all the afk'ers are placed in lobbies together. If this becomes over automated, its possible to be matched with present players, in which case the bot will likely place 7/8 every time.

**Comment by Benjamin-Berger** [comment]
> Agreed, my best idea for solving the useless fight for 1st/2nd was checking to see if there are six 0's on the scoreboard (meaning everyone but you and the other person is out), but might be hard to get a good capture/precision.
> 

I set one for top 4 (4 others dead). I had to set the threshold to .97 but it works decently. There was one game where 3 were dead and the 4th had 1 hp. This was still detected for some reason. I can try setting to .98 but .99 did not work with my capture.
