### ISSUE TITLE
Not autoqueuing on Garena client

### ISSUE THREAD

**Issue by LOKI696** [Detergent13/tft-bot#90]
i play in garena.

when i finish game, not auto next.

like this

https://ibb.co/QHKM1LW

**Comment by Detergent13** [comment]
Seems to me that your lobby somehow crashed, since the button is greyed out. This is probably a client issue rather than a bot issue

**Comment by LOKI696** [comment]
> Seems to me that your lobby somehow crashed, since the button is greyed out. This is probably a client issue rather than a bot issue

yes, i think is garena problem , trash garena add  some Gacha lottery  and Advertisement Sweepstakes

have something can fix this problem  plz ?

**Comment by ImmaGOOD** [comment]
Same Problem 

Because Advertisement page Random popup after finish game so bot not recognized and not continue 

Please fix this for garena player

**Comment by Detergent13** [comment]
> Same Problem 
> 
> Because Advertisement page Random popup after finish game so bot not recognized and not continue 
> 
> Please fix this for garena player 

If you want it to be fixed I'd recommend making a fork and doing it yourself.

I won't be adding official support for Garena simply because I don't have an account or a way to test. Also has the potential to break things for the normal client. 

Sorry about the Garena client though, it really seems like it sucks.
